# Generated by Django 5.0 on 2023-12-10 14:57

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('expenses', '0001_initial'),
        ('teachers', '0003_alter_teacher_user'),
    ]

    operations = [
        migrations.AddField(
            model_name='expense',
            name='teacher',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='teachers.teacher'),
            preserve_default=False,
        ),
    ]
