# Generated by Django 5.0 on 2023-12-10 14:11

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('vehicles', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='TeacherDocumentation',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('dni', models.FileField(upload_to='dni')),
                ('circulation_permission', models.FileField(upload_to='circulation_permission')),
                ('excersise_authorization', models.FileField(upload_to='excersise_authorization')),
                ('distintive', models.FileField(upload_to='distintive')),
            ],
        ),
        migrations.CreateModel(
            name='Teacher',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
                ('vehicles', models.ManyToManyField(related_name='teachers', to='vehicles.vehicle')),
                ('documentation', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='teacher', to='teachers.teacherdocumentation')),
            ],
        ),
    ]
