# Generated by Django 5.0 on 2023-12-10 13:44

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Vehicle',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('model', models.IntegerField()),
                ('year', models.IntegerField()),
                ('image', models.CharField(max_length=1000)),
                ('plate_number', models.CharField(max_length=100)),
                ('data', models.JSONField()),
            ],
        ),
        migrations.CreateModel(
            name='VehicleDocumentation',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('technical_sheet', models.FileField(upload_to='technical_sheet')),
                ('circulation_document', models.FileField(upload_to='circulation_document')),
                ('circulation_permission', models.FileField(upload_to='circulation_permission')),
                ('vehicle', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='vehicle_documentation', to='vehicles.vehicle')),
            ],
        ),
    ]
